/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GithubStats {
        "bgColor": string;
        "hideBorder": string;
        "textColor": string;
        "theme": string;
        "username": string;
    }
    interface GithubStreakStats {
        "bgColor": string;
        "hideBorder": string;
        "textColor": string;
        "theme": string;
        "username": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLGithubStatsElement extends Components.GithubStats, HTMLStencilElement {
    }
    var HTMLGithubStatsElement: {
        prototype: HTMLGithubStatsElement;
        new (): HTMLGithubStatsElement;
    };
    interface HTMLGithubStreakStatsElement extends Components.GithubStreakStats, HTMLStencilElement {
    }
    var HTMLGithubStreakStatsElement: {
        prototype: HTMLGithubStreakStatsElement;
        new (): HTMLGithubStreakStatsElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "github-stats": HTMLGithubStatsElement;
        "github-streak-stats": HTMLGithubStreakStatsElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface GithubStats {
        "bgColor"?: string;
        "hideBorder"?: string;
        "textColor"?: string;
        "theme"?: string;
        "username"?: string;
    }
    interface GithubStreakStats {
        "bgColor"?: string;
        "hideBorder"?: string;
        "textColor"?: string;
        "theme"?: string;
        "username"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "github-stats": GithubStats;
        "github-streak-stats": GithubStreakStats;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "github-stats": LocalJSX.GithubStats & JSXBase.HTMLAttributes<HTMLGithubStatsElement>;
            "github-streak-stats": LocalJSX.GithubStreakStats & JSXBase.HTMLAttributes<HTMLGithubStreakStatsElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
